// Copyright The Mumble Developers. All rights reserved.
// Use of this source code is governed by a BSD-style license
// that can be found in the LICENSE file at the root of the
// Mumble source tree or at <https://www.mumble.info/LICENSE>.

#include "modules/IServerModule.h"

// This empty implementation file is needed to ensure that the Qt meta-object system 
// properly generates the vtable and staticMetaObject for the IServerModule class.
// The IServerModule class is an interface with pure virtual methods, but we still 
// need to have this file to satisfy the linker and Qt's meta-object system.

// The moduleEvent signal is already declared in the header file and will be 
// automatically generated by the Qt meta-object compiler (moc).